QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master/ViewModels/EventsViewModel.cs
using QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.Models;

namespace QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.ViewModels
{
    public class EventsViewModel
    {
        public PaginatedList<EventsModel> ? RunningEvents { get; set; }
        public PaginatedList<EventsModel> ? UpcomingEvents { get; set; }
        public PaginatedList<EventsModel> ? EndedEvents { get; set; }
    }
}

QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master/Areas/Admin/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.Data;
using QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using OfficeOpenXml;
using static Microsoft.IO.RecyclableMemoryStreamManager;
using Microsoft.AspNetCore.Identity;
using QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.ViewModels;
using QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.Controllers;
using iTextSharp.text;
using iTextSharp.text.pdf;
using X.PagedList;
namespace QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.Areas.Admin.Controllers
{ 
    [Area("Admin")]
   
    public class EventsController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public EventsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment) : base(context)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
       
        }
        [Authorize(Roles = "Quản lý, Trưởng phòng")]
        // GET: Admin/Events
        public async Task<IActionResult> Index()
        {
            var events = await _context.Events
                .Where(e => e.EventStatus == "1")
                .OrderByDescending(e => e.EventStartDate)
                .ToListAsync();

            return View(events);
        }


        [Authorize(Roles = "Quản lý, Trưởng phòng")]
        public async Task<IActionResult> UpcomingEvents()
        {
            var upcomingEvents = await _context.Events .Where(e => e.EventStatus == "2").ToListAsync();

            return View(upcomingEvents);
        }
        [Authorize(Roles = "Quản lý, Trưởng phòng")]
        public async Task<IActionResult> EndedEvents()
        {
            // Lấy tất cả sự kiện có EventStatus == "0"
            var endedEvents = await _context.Events.Where(e => e.EventStatus == "0").ToListAsync();

            // Đếm số lượng đăng ký cho từng sự kiện
            foreach (var eventDetail in endedEvents)
            {
                eventDetail.NumberRegistrations = await _context.EventRegistrations
                    .CountAsync(r => r.EventId == eventDetail.EventID);

                _context.Update(eventDetail);
            }

            await _context.SaveChangesAsync();

            return View(endedEvents);
        }
        [Authorize(Roles = "Quản lý")]
        public async Task<IActionResult> RegistrationList(int eventId)
        {
            var eventDetail = await _context.Events
                .Include(e => e.Registrations)
                .FirstOrDefaultAsync(e => e.EventID == eventId);

            if (eventDetail == null)
            {
                return NotFound();
            }

            // Lấy danh sách đăng ký tham gia sự kiện
            var registrations = await _context.EventRegistrations
                .Where(r => r.EventId == eventId)
                .Include(r => r.Customers)
                .OrderByDescending(r => r.RegistrationDate)
                .ToListAsync();

            ViewBag.EventName = eventDetail.EventName;
            ViewBag.EventId = eventDetail.EventID;
            ViewBag.UserName = HttpContext.Session.GetString("Username");
            return View(registrations);
        }


        [Authorize(Roles = "Trưởng phòng")]
        public IActionResult Create()
        {
            ViewBag.EventLocations = GetEventLocationOptions();
            ViewBag.SelectStatus = GetEventStatusOptions();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EventsModel model, string newLocationInput)
        {
            if (model.EventStartDate <= DateTime.Now)
            {
                ModelState.AddModelError("EventStartDate", "Ngày bắt đầu sự kiện phải lớn hơn ngày hiện tại.");
            }

            if (model.EventEndDate <= DateTime.Now)
            {
                ModelState.AddModelError("EventEndDate", "Ngày kết thúc sự kiện phải lớn hơn ngày hiện tại.");
            }

            if (model.EventEndDate <= model.EventStartDate)
            {
                ModelState.AddModelError("EventEndDate", "Ngày kết thúc sự kiện phải lớn hơn ngày bắt đầu sự kiện.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.FrontImg != null)
                    {
                        string filePath = SaveFile(model.FrontImg);
                        model.ImgUrl = filePath;
                    }

                    if (!string.IsNullOrEmpty(newLocationInput))
                    {
                        // Nếu người dùng đã nhập địa điểm mới
                        model.EventLocation = newLocationInput;
                    }

                    _context.Add(model);
                    await _context.SaveChangesAsync();

                    return Json(new { success = true, eventId = model.EventID, message = "Sự kiện đã được tạo thành công." });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Đã xảy ra lỗi: {ex.Message}");
                    return Json(new { errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage) });
                }
            }

            return Json(new { errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage) });
        }


        private string SaveFile(IFormFile file)
        {
            string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "uploads");
            string uniqueFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                file.CopyTo(fileStream);
            }
            return "/uploads/" + uniqueFileName;
        }
        [Authorize(Roles = "Trưởng phòng")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventsModel = await _context.Events.FindAsync(id);
            if (eventsModel == null)
            {
                return NotFound();
            }

            ViewBag.EventLocations = GetEventLocationOptions();
            ViewBag.SelectStatus = GetEventStatusOptions();
            return View(eventsModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EventsModel model)
        {
            if (id != model.EventID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.FrontImg != null)
                    {
                        if (!string.IsNullOrEmpty(model.ImgUrl))
                        {
                            DeleteFile(model.ImgUrl);
                        }
                        // Lưu hình ảnh mới
                        string filePath = SaveFile(model.FrontImg);
                        model.ImgUrl = filePath;
                    }

                    _context.Update(model);
                    await _context.SaveChangesAsync();
                    return Json(new { success = true, eventId = model.EventID, message = "Sự kiện đã được cập nhật thành công." });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventModelExists(model.EventID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            return Json(new { errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage) });
        }

        private bool EventModelExists(int id)
        {
            return _context.Events.Any(e => e.EventID == id);
        }

        private void DeleteFile(string filePath)
        {
            string fullPath = Path.Combine(_webHostEnvironment.WebRootPath, filePath.TrimStart('/'));
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
        }
        [Authorize(Roles = "Trưởng phòng")]
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var eventsModel = await _context.Events.FindAsync(id);
            if (eventsModel == null)
            {
                return NotFound();
            }

            try
            {
                _context.Events.Remove(eventsModel);
                await _context.SaveChangesAsync();
                return Json(new { success = true, message = "Sự kiện đã được xóa thành công." });
            }
            catch (Exception ex)
            {
                return Json(new { errors = $"Đã xảy ra lỗi: {ex.Message}" });
            }
        }
        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.EventID == id);
        }
       
        public List<SelectListItem> GetEventStatusOptions()
        {
            var options = new List<SelectListItem>
            {
                new SelectListItem { Value = "0", Text = "Ẩn sự kiện" },
                new SelectListItem { Value = "1", Text = "Đang diễn ra" },
                new SelectListItem { Value = "2", Text = "Sắp diễn ra" },
            };
            return options;
        }
        public List<SelectListItem> GetEventLocationOptions()
        {
            // Lấy danh sách các EventLocation từ dữ liệu
            var locations = _context.Events.Select(e => e.EventLocation).Distinct().ToList();

QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master/Controllers/EventsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.Data;
using QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.Models;
using QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.ViewModels;

namespace QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.Controllers
{
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> LoadAllRunningEvents(int runningPageNumber = 1, int runningPageSize = 10)
        {
            var runningEventsQuery = _context.Events
               .Where(e => e.EventStatus == "1")
               .OrderByDescending(e => e.EventStartDate)
               .AsQueryable();


            var runningEvents = await PaginatedList<EventsModel>.CreateAsync(runningEventsQuery.AsNoTracking(), runningPageNumber, runningPageSize);

            var viewModel = new EventsViewModel
            {
                RunningEvents = runningEvents,
            };

            return View(viewModel);
        }
        public async Task<IActionResult> LoadAllUpcoming(int upcomingPageNumber = 1, int upcomingPageSize = 10)
        {
            var upcomingEventsQuery = _context.Events
              .Where(e => e.EventStatus == "2")
              .OrderBy(e => e.EventStartDate)
              .AsQueryable();


            var upcomingEvents = await PaginatedList<EventsModel>.CreateAsync(upcomingEventsQuery.AsNoTracking(), upcomingPageNumber, upcomingPageSize);

            var viewModel = new EventsViewModel
            {
                UpcomingEvents = upcomingEvents,
            };

            return View(viewModel);
        }
        public async Task<IActionResult> LoadAllEndedEvents(int endedPageNumber = 1, int endedPageSize = 10)
        {
            var endedEventsQuery = _context.Events
                .Where(e => e.EventStatus == "0")
                .OrderByDescending(e => e.EventEndDate)
                .AsQueryable();

            var endedEvents = await PaginatedList<EventsModel>.CreateAsync(endedEventsQuery.AsNoTracking(), endedPageNumber, endedPageSize);

            var viewModel = new EventsViewModel
            {
                EndedEvents = endedEvents
            };

            return View(viewModel); 
        }

      

        // GET: /Events/Detail
        public async Task<IActionResult> Detail(int eventId)
        {
            var eventDetail = await _context.Events.FirstOrDefaultAsync(e => e.EventID == eventId);

            if (eventDetail == null)
            {
                return NotFound();
            }

            // Đếm số lượng đăng ký cho sự kiện này
            eventDetail.NumberRegistrations = await _context.EventRegistrations
                                              .CountAsync(r => r.EventId == eventId);

            return View(eventDetail);
        }

        public async Task<IActionResult> Register(int eventId)
        {
            var eventModel = await _context.Events
                                           .Include(e => e.Registrations)
                                           .FirstOrDefaultAsync(e => e.EventID == eventId);
            if (eventModel == null)
            {
                return NotFound();
            }

            var registrationModel = new EventRegistrationModel
            {
                EventId = eventModel.EventID,
                Event = eventModel,
                Customers = new CustomersModel()
            };

            return View(registrationModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(EventRegistrationModel registrationModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var eventModel = await _context.Events.FindAsync(registrationModel.EventId);
                    if (eventModel == null)
                    {
                        ModelState.AddModelError("", "Sự kiện không có. Lỗi");
                        return Json(new { success = false, message = "Sự kiện không có. Lỗi" });
                    }

                    registrationModel.Event = eventModel;

                    // Tìm khách hàng bằng email
                    var customer = await _context.Customers
                                                 .FirstOrDefaultAsync(c => c.CustomerEmail == registrationModel.Customers.CustomerEmail);

                    if (customer != null)
                    {
                        // Kiểm tra xem khách hàng đã đăng ký sự kiện này chưa
                        var existingRegistration = await _context.EventRegistrations
                            .FirstOrDefaultAsync(r => r.EventId == registrationModel.EventId && r.CustomerId == customer.CustomerId);

                        if (existingRegistration != null)
                        {
                            return Json(new { success = false, message = "Email này đã đăng ký cho sự kiện." });
                        }
                        // Gán CustomerId cho registrationModel
                        registrationModel.CustomerId = customer.CustomerId;
                    }
                    else
                    {
                        // Tạo một khách hàng mới nếu không tìm thấy
                        var newCustomer = new CustomersModel
                        {
                            CustomerName = registrationModel.Customers.CustomerName,
                            CustomerEmail = registrationModel.Customers.CustomerEmail,
                            CustomerPhone = registrationModel.Customers.CustomerPhone
                        };
                        _context.Customers.Add(newCustomer);
                        await _context.SaveChangesAsync();

                        registrationModel.CustomerId = newCustomer.CustomerId;
                    }
                    registrationModel.RegistrationDate = DateTime.UtcNow;

                    // Xóa thông tin khách hàng để tránh lưu trùng lặp vào EventRegistrations
                    registrationModel.Customers = null;

                    // Thêm bản đăng ký vào cơ sở dữ liệu
                    _context.EventRegistrations.Add(registrationModel);
                    await _context.SaveChangesAsync();

                    // Chuyển hướng đến trang thành công hoặc hiển thị thông báo thành công
                    return Json(new { success = true });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Đã xảy ra lỗi: {ex.Message}");
                    return Json(new { success = false, message = ex.Message });
                }
            }

            var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
            return Json(new { success = false, errors });
        }

    }
}

QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master/Areas/Admin/Views/Events/EndedEvents.cshtml
@model IEnumerable<QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.Models.EventsModel>
@{
    ViewData["Title"] = "Danh sách sự kiện";
    Layout = "~/Areas/Admin/Shared/_LayoutAdmin.cshtml";
}

<h2>Sự kiện đã kết thúc</h2>

@{
    if (User.IsInRole("Trưởng phòng"))
    {
        <a href="#" id="btnOpenCreateModal" class="btn btn-success m-2">Tạo mới sự kiện</a>
    }
}

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Ảnh</th>
                <th scope="col">Tên sự kiện</th>
                <th scope="col">Ngày bắt đầu</th>
                <th scope="col">Ngày kết thúc</th>
                <th scope="col">Địa điểm</th>
                <th scope="col">Trạng thái</th>
                <th scope="col">Số lượt đăng ký</th>
                <th scope="col">Thao tác</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="width: 150px">
                        <img src="@item.ImgUrl" class="img-thumbnail" style="width: 100px; height: 75px;" />
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.EventName)</td>
                    <td>@item.EventStartDate.ToString("dd/MM/yyyy HH:mm")</td>
                    <td>@item.EventEndDate.ToString("dd/MM/yyyy HH:mm")</td>
                    <td>@Html.DisplayFor(modelItem => item.EventLocation)</td>
                    <td>
                        @{
                            switch (item.EventStatus)
                            {
                                case "1":
                                    <span class="badge badge-success">Đang diễn ra</span>
                                    break;
                                case "0":
                                    <span class="badge badge-secondary">Đã kết thúc</span>
                                    break;
                                case "2":
                                    <span class="badge badge-primary">Sắp diễn ra</span>
                                    break;
                                default:
                                    <span class="badge badge-warning">Không xác định</span>
                                    break;
                            }
                        }
                    </td>
                    <td class="text-center">
                        <span class="badge badge-success">@item.NumberRegistrations</span>
                        <i class="fas fa-users ml-1"></i>
                    </td>
                    <td>
                        <a href="@Url.Action("RegistrationList", "Events", new { eventId = item.EventID })" class="btn btn-info btn-sm" title="Xem đăng ký" style="width: 120px">
                            <i class="fas fa-eye"></i> Xem chi tiết
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>


<!-- Modal -->
<div class="modal fade" id="createEventModal" tabindex="-1" role="dialog" aria-labelledby="createEventModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createEventModalLabel">Tạo mới sự kiện</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="createEventModalContent"></div>
            </div>
        </div>
    </div>
</div>
<script src="~/js/Events.js"></script>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function () {
            // Sự kiện click vào nút "Tạo mới sự kiện"
            $('#btnOpenCreateModal').click(function () {
                openModal('@Url.Action("Create", "Events", new { area = "Admin" })');
            });
            // Sự kiện click vào nút "Lưu" trong form "Tạo mới sự kiện"
            $(document).on('click', '#btnCreateEvent', function () {
                var formData = new FormData($('#createEventForm')[0]);
                ajaxPost('@Url.Action("Create", "Events")', formData);
            });

            // Sự kiện click vào nút "Chỉnh sửa" của một sự kiện
            $(document).on('click', '.edit-link', function () {
                var eventId = $(this).data('id');
                openModal('@Url.Action("Edit", "Events", new { area = "Admin" })?id=' + eventId);
            });


            /* $(document).on('click', '.registration-list-link', function () {
                var eventId = $(this).data('id');
                openModal('@Url.Action("RegistrationList", "Events", new { area = "Admin" })?id=' + eventId);
            });*/

            // Sự kiện click vào nút "Lưu" trong form "Chỉnh sửa sự kiện"
            $(document).on('click', '#btnSaveEvent', function () {
                var formData = new FormData($('#editEventForm')[0]);
                var eventId = $('input[name="EventID"]').val();
                ajaxPost('@Url.Action("Edit", "Events")/' + eventId, formData);
            });

            // Sự kiện click vào nút "Đóng" trong modal
            $(document).on('click', '[data-dismiss="modal"]', function () {
                $('#createEventModal').modal('hide');
            });

            // Xử lý sự kiện click xóa sự kiện
            $('.delete-link').click(function () {
                if (confirm('Bạn có chắc chắn muốn xóa sự kiện này?')) {
                    var eventId = $(this).data('id');
                    ajaxPost('@Url.Action("Delete", "Events", new { area = "Admin" })/' + eventId, {});
                }
            });

        });
        function previewImage(input) {
            var preview = document.getElementById('imagePreview');
            var file = input.files[0];

            if (file) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    preview.src = e.target.result;
                    preview.style.display = 'block';
                }

                reader.readAsDataURL(file);
            }
        }

    </script>

}

QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master/Areas/Admin/Views/Events/Index.cshtml
@model IEnumerable<QL_ToChucSuKien_TTSKCĐVHTKNTBD_Master.Models.EventsModel>
@{
    ViewData["Title"] = "Danh sách sự kiện";
    Layout = "~/Areas/Admin/Shared/_LayoutAdmin.cshtml";
}

<h2>Sự kiện đang diễn ra</h2>

@{
    if (User.IsInRole("Trưởng phòng"))
    {
                <a href="#" id="btnOpenCreateModal" class="btn btn-success m-2">Tạo mới sự kiện</a>
    }
}


<table id="eventsTable" class="table table-striped table-bordered display" style="text-align: center;">
    <thead class="thead-dark">
        <tr>
            <th>Ảnh</th>
            <th>Tên sự kiện</th>
            <th>Ngày bắt đầu</th>
            <th>Ngày kết thúc</th>
            <th>Địa điểm</th>
            <th>Thao tác</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="vertical-align: middle;">
                    <img src="@item.ImgUrl" style="width: 75px; height: 75px; object-fit: cover; border-radius: 50%;" />
                </td>
                <td style="vertical-align: middle;">@Html.DisplayFor(modelItem => item.EventName)</td>
                <td style="vertical-align: middle;">@item.EventStartDate.ToString("dd/MM/yyyy HH:mm")</td>
                <td style="vertical-align: middle; width: 140px;">@item.EventEndDate.ToString("dd/MM/yyyy HH:mm")</td>
                <td style="vertical-align: middle;">@Html.DisplayFor(modelItem => item.EventLocation)</td>
                <td style="vertical-align: middle; width:190px">
                    @{
                        if (User.IsInRole("Trưởng phòng"))
                        {
                                    <div style="margin-bottom: 5px;">
                                        <a href="#" class="btn btn-primary btn-block edit-link" data-id="@item.EventID" title="Edit">
                                            <i class="fas fa-edit"></i> Chỉnh sửa
                                        </a>
                                    </div>
                                    <div style="margin-bottom: 5px;">
                                        <a href="#" class="btn btn-danger btn-block delete-link" data-id="@item.EventID" title="Delete">
                                            <i class="fas fa-trash-alt"></i> Xóa
                                        </a>
                                    </div>
                        }
                    }
                    <div>
                        <a href="@Url.Action("RegistrationList", "Events", new { eventId = item.EventID })" class="btn btn-success btn-block" title="Xem đăng ký">
                            <i class="fas fa-eye"></i> Xem đăng ký
                        </a>
                    </div>
                </td>


            </tr>
        }
    </tbody>
</table>


<!-- Modal -->
<div class="modal fade" id="createEventModal" tabindex="-1" role="dialog" aria-labelledby="createEventModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createEventModalLabel">Tạo mới sự kiện</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="createEventModalContent"></div>
            </div>
        </div>
    </div>
</div>
<script src="~/js/Events.js"></script>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function () {
            // Sự kiện click vào nút "Tạo mới sự kiện"
            $('#btnOpenCreateModal').click(function () {
                openModal('@Url.Action("Create", "Events", new { area = "Admin" })');
            });

            // Sự kiện click vào nút "Lưu" trong form "Tạo mới sự kiện"
            $(document).on('click', '#btnCreateEvent', function () {
                var formData = new FormData($('#createEventForm')[0]);
                ajaxPost('@Url.Action("Create", "Events")', formData);
            });

            // Sự kiện click vào nút "Chỉnh sửa" của một sự kiện
            $(document).on('click', '.edit-link', function () {
                var eventId = $(this).data('id');
                openModal('@Url.Action("Edit", "Events", new { area = "Admin" })?id=' + eventId);
            });

            // Sự kiện click vào nút "Lưu" trong form "Chỉnh sửa sự kiện"
            $(document).on('click', '#btnSaveEvent', function () {
                var formData = new FormData($('#editEventForm')[0]);
                var eventId = $('input[name="EventID"]').val();
                ajaxPost('@Url.Action("Edit", "Events")/' + eventId, formData);
            });

            // Sự kiện click vào nút "Đóng" trong modal
            $(document).on('click', '[data-dismiss="modal"]', function () {
                $('#createEventModal').modal('hide');
            });

            // Xử lý sự kiện click xóa sự kiện
            $('.delete-link').click(function () {
                if (confirm('Bạn có chắc chắn muốn xóa sự kiện này?')) {
                    var eventId = $(this).data('id');
                    ajaxPost('@Url.Action("Delete", "Events", new { area = "Admin" })/' + eventId, {});
                }
            });
        
        });

            function previewImage(input) {
                var preview = document.getElementById('imagePreview');
                var file = input.files[0];

                if (file) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        preview.src = e.target.result;
                        preview.style.display = 'block';
                    }

                    reader.readAsDataURL(file);
                }
            }
        $(document).ready(function () {
            $('#eventsTable').DataTable({
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.11.5/i18n/vi.json"
                },
                "paging": true,
                "ordering": true,
                "info": true,
                "pageLength": 10,
                layout: {
                    topStart: {
                        buttons: [
                            {
                                extend: 'copy',
                                text: '<i class="fas fa-copy"></i> Sao chép',
                                className: 'btn btn-primary'
                            },
                            {
                                extend: 'csv',
                                text: '<i class="fas fa-file-csv"></i> CSV',
                                className: 'btn btn-primary'
                            },
                            {
                                extend: 'excel',
                                text: '<i class="fas fa-file-excel"></i> Excel',
                                className: 'btn btn-success'
                            },
                            {
                                extend: 'pdf',
                                text: '<i class="fas fa-file-pdf"></i> PDF',
                                className: 'btn btn-danger'
                            },
                            {
                                extend: 'print',
                                text: '<i class="fas fa-print"></i> In',
                                className: 'btn btn-info'
                            }
                        ]
                    }
                }
                      
            });
        });

    </script>
}